// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgmkfrwjhutxrbbwzxnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnbWtmcndqaHV0eHJiYnd6eG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczOTE0NjQsImV4cCI6MjA1Mjk2NzQ2NH0.eZ8t1YJBx8at3vigHfVierNezPyPhtMzpCwU69GcC7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);